export enum TabType {
    REFRESH_TAB = "REFRESH_TAB",
    COLLAPSED_TAB = "COLLAPSED_TAB",
    SETTINGS_TAB = "SETTINGS_TAB",
    BUILT_IN_ATTR_TAB = "BUILT_IN_ATTR_TAB",
    CUSTOM_ATTR_TAB = "CUSTOM_ATTR_TAB",
    DATABASE_ATTR_TAB = "DATABASE_ATTR_TAB",
}